<?php

return [

    'AI vertaaloortjes en vertaalapparaten' => [
        'filters' => [
            'vertaaloortje',
            'vertaal oortje',
            'vertaler oortje',
            'AI vertaalapparaat',
            'AI vertaaloortje',
            'real-time vertalen',
            'spraak vertalen',
            'spraakherkenning',
            'live vertalen',
            'realtime vertaling',
            'AI vertaling',
            'handsfree vertaling',
            'vertalen zonder app',
            'bluetooth vertaalapparaat',
            'spraak naar spraak vertaling',
            'slimme vertaler',
            'automatische vertaling',
            'draadloos vertaalapparaat',
            'babbeloortje',
            'AI tolk',
            'digitale tolk',
            'multilingual vertaler',
            'internationale communicatie',
            'AI spraakvertaler',
            'mobiele vertaler',
            'taalvertaler',
            'spraakconverter',
        ],
    ],

    'airfryers met dubbele lade' => [
        'filters' => [
            'dubbele lade',
            '2 lades',
            'twee lades',
            'dual zone',
            'dual basket',
            'twee compartimenten',
            'twee vakken',
            'twee zones',
            '2 compartimenten',
            '2 manden',
            'twee manden',
            'split fryer',
            'dual airfryer',
            'twin zone',
            'individueel instelbare manden',
            'aparte manden',
            'aparte lades',
            'gescheiden lades',
            'losse lades',
            'losse manden',
        ],
    ],

    'elektrische tandenborstels' => [
        'filters' => [],
    ],

    'loopbanden' => [
        'filters' => [],
    ],

    'bonen koffiemachines' => [
        'filters' => [
            'bonenmachine',
            'volautomaat',
            'halfautomaat',
            'pistonmachine',
            'koffiemolen geïntegreerd',
            'koffiebonen reservoir',
            'automatische melkschuimer',
            'stoompijpje',
            'melkschuimer',
            'espresso volautomaat',
            'koffiebonen',
            'koffiezetapparaat met bonen',
            'geïntegreerde koffiemolen',
            'koffiemachine met bonen',
            'koffie apparaat met bonen',
        ],
    ],

    'massagekussens' => [
        'filters' => [
            'massagekussen',
            'rugmassagekussen',
            'nekmassagekussen',
            'elektrisch massagekussen',
            'massage kussen',
            'warmtekussen massage',
            'shiatsu kussen',
            'stoelmassagekussen',
            'auto massagekussen',
            'draagbaar massagekussen',
            'massage pad',
            'massagekussen met warmte',
            'infrarood massagekussen',
            'nek en schouder massagekussen',
            'elektrisch rugkussen',
            'elektrisch nekkussen',
        ],
    ],

    'hondenvoerautomaten' => [
        'filters' => [
            'hond',
            'honden',
            'hondenvoer',
            'hondenbrokken',
            'hondenvoeding',
            'hondenautomaat',
            'hondenvoerautomaat',
            'hondendispenser',
            'hondenvoerdispenser',
            'automatische hondenvoeder',
            'hondenvoer automaat',
            'honden voer automaat',
            'honden voerautomaat',
        ],
    ],

    'massagestoel' => [
        'filters' => [
            'massagestoel',
            'massage stoel',
            'massagefauteuil',
            'massage fauteuil',
            'elektrische massagestoel',
            'shiatsu stoel',
            'shiatsu fauteuil',
            'massage chair',
            'relaxstoel massage',
            'massagestoel elektrisch',
            'volledige lichaam massage',
            'zero gravity massage',
            'massage relax stoel',
            'massage zetel',
            'relaxstoel met massage',
            'elektrische relaxstoel',
            'massagestoel shiatsu',
            'tv stoel massage',
            'leer massagestoel',
            'draadloze massagestoel',
            'massage loungestoel',
            'wellness stoel',
            'massage',
            'spa stoel',
            'therapeutische stoel',
            'rugmassage stoel',
            'beenmassage stoel',
            'voetmassage stoel',
            'massage stoel zwart',
            'massage stoel bruin',
            'massage stoel wit',
            'massage stoel beige',
        ],
    ],

];
