<?php

return [
    'airfryermetdubbelelade.nl' => [
        ['name' => 'Aantal lades', 'priority' => 1],
        ['name' => 'Totale inhoud (liter)', 'priority' => 1],
        ['name' => 'Inhoud per lade (liter)', 'priority' => 1],
        ['name' => 'Automatische programma’s', 'priority' => 2],
        ['name' => 'Minimale temperatuur', 'priority' => 2],
        ['name' => 'Maximale temperatuur', 'priority' => 2],
        ['name' => 'Vermogen (Watt)', 'priority' => 1],
        ['name' => 'Warmhoudfunctie', 'priority' => 2],
        ['name' => 'Type bediening', 'priority' => 2],
        ['name' => 'Koele wand', 'priority' => 3],
        ['name' => 'Antislipvoetjes', 'priority' => 3],
        ['name' => 'Timerfunctie', 'priority' => 1],
        ['name' => 'Airfry-functie', 'priority' => 2],
        ['name' => 'Vaatwasserbestendige onderdelen', 'priority' => 1],
        ['name' => 'Snoerlengte', 'priority' => 3],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Inclusief kookrekjes', 'priority' => 2],
        ['name' => 'Max aantal programma’s', 'priority' => 2],
        ['name' => 'Smart-functies / app', 'priority' => 3],
        ['name' => 'Opwarmfunctie', 'priority' => 2],
    ],
    'beste-elektrischestep.nl' => [
        ['name' => 'Maximale snelheid', 'priority' => 1],
        ['name' => 'Actieradius (km)', 'priority' => 1],
        ['name' => 'Laadtijd', 'priority' => 1],
        ['name' => 'Wielmaat', 'priority' => 2],
        ['name' => 'Maximaal draaggewicht', 'priority' => 1],
        ['name' => 'Vermogen motor (Watt)', 'priority' => 2],
        ['name' => 'Voor- en achtervering', 'priority' => 2],
        ['name' => 'Remtype (schijf / trommel / E-ABS)', 'priority' => 2],
        ['name' => 'Waterdichtheid (IP-rating)', 'priority' => 2],
        ['name' => 'Gewicht step', 'priority' => 2],
        ['name' => 'Verlichting voor/achter', 'priority' => 2],
        ['name' => 'Display met snelheidsinfo', 'priority' => 2],
        ['name' => 'Cruise control', 'priority' => 3],
        ['name' => 'Bluetooth / app-connectie', 'priority' => 3],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Oprolbaar / inklapbaar', 'priority' => 1],
        ['name' => 'Materiaal frame', 'priority' => 3],
        ['name' => 'Type banden (lucht / massief)', 'priority' => 2],
        ['name' => 'Hellingshoek', 'priority' => 3],
        ['name' => 'Verwisselbare accu', 'priority' => 3],
    ],
    'beste-massagegun.nl' => [
        ['name' => 'Aantal snelheden', 'priority' => 1],
        ['name' => 'Aantal opzetstukken', 'priority' => 2],
        ['name' => 'Percussie per minuut', 'priority' => 1],
        ['name' => 'Accuduur', 'priority' => 1],
        ['name' => 'Laadtijd', 'priority' => 2],
        ['name' => 'Ingebouwd display', 'priority' => 2],
        ['name' => 'Instelbare intensiteit', 'priority' => 1],
        ['name' => 'Maximaal geluidsniveau', 'priority' => 2],
        ['name' => 'Gebruik tijdens opladen', 'priority' => 3],
        ['name' => 'Draadloos (op accu)', 'priority' => 1],
        ['name' => 'Oplaadtype (USB-C / adapter)', 'priority' => 2],
        ['name' => 'Gewicht massagegun', 'priority' => 2],
        ['name' => 'Inclusief opbergdoos', 'priority' => 2],
        ['name' => 'Verlichte bediening', 'priority' => 3],
        ['name' => 'Automatische uitschakeling', 'priority' => 3],
        ['name' => 'Materiaal behuizing', 'priority' => 3],
        ['name' => 'Opwarmfunctie', 'priority' => 3],
        ['name' => 'Lengte handvat', 'priority' => 3],
        ['name' => 'App-integratie', 'priority' => 3],
        ['name' => 'Garantieperiode', 'priority' => 2],
    ],
    'bestebeveiligingscamera.nl' => [
        ['name' => 'Beeldkwaliteit (resolutie)', 'priority' => 1],
        ['name' => 'Nachtzicht', 'priority' => 1],
        ['name' => 'Bewegingsdetectie', 'priority' => 1],
        ['name' => 'Binnen of buiten', 'priority' => 1],
        ['name' => 'Opslagoptie (cloud/SD)', 'priority' => 2],
        ['name' => 'Live meekijken via app', 'priority' => 1],
        ['name' => 'Audio (2-weg)', 'priority' => 2],
        ['name' => 'Kijkhoek', 'priority' => 2],
        ['name' => 'App ondersteuning', 'priority' => 1],
        ['name' => 'Aansluiting (draadloos/bedraad)', 'priority' => 2],
        ['name' => 'IP-certificering (waterdicht)', 'priority' => 2],
        ['name' => 'Sirene of alarmfunctie', 'priority' => 3],
        ['name' => 'Opslagcapaciteit (GB)', 'priority' => 2],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Gezichtsherkenning', 'priority' => 3],
        ['name' => 'Installatiegemak', 'priority' => 2],
        ['name' => 'Compatibel met Google/Alexa', 'priority' => 2],
        ['name' => 'Stroomvoorziening (batterij/net)', 'priority' => 2],
        ['name' => 'Rotatie op afstand', 'priority' => 3],
        ['name' => 'Garantie', 'priority' => 2],
    ],
    'aivertalerapparaat.nl' => [
        ['name' => 'Aantal ondersteunde talen', 'priority' => 1],
        ['name' => 'Vertaalnauwkeurigheid (%)', 'priority' => 1],
        ['name' => 'Modus (touch/speaker)', 'priority' => 1],
        ['name' => 'Handsfree functionaliteit', 'priority' => 2],
        ['name' => 'Bluetooth-versie', 'priority' => 2],
        ['name' => 'Batterijduur (maximaal)', 'priority' => 1],
        ['name' => 'Accuduur bij intensief gebruik', 'priority' => 2],
        ['name' => 'Oplaadtijd', 'priority' => 2],
        ['name' => 'Geschikt voor (iOS/Android)', 'priority' => 1],
        ['name' => 'Noise cancelling', 'priority' => 2],
        ['name' => 'Touch bediening', 'priority' => 1],
        ['name' => 'Waterbestendig (IP-certificering)', 'priority' => 2],
        ['name' => 'Inclusief opzetstukjes (maten)', 'priority' => 3],
        ['name' => 'Gebruik met app mogelijk', 'priority' => 1],
        ['name' => 'Gebruik als gewone oordopjes', 'priority' => 2],
        ['name' => 'Inclusief microfoon', 'priority' => 1],
        ['name' => 'Geschikt voor telefoongesprekken', 'priority' => 2],
        ['name' => 'Meegeleverde accessoires', 'priority' => 2],
        ['name' => 'Oplaadtype (USB-C / Micro-USB)', 'priority' => 3],
        ['name' => 'Draagcomfort / pasvorm opties', 'priority' => 2],
        ['name' => 'Inclusief display', 'priority' => 3],
        ['name' => 'Taal handleiding', 'priority' => 3],
        ['name' => 'CE-markering aanwezig', 'priority' => 3],
        ['name' => 'Introductiejaar', 'priority' => 3],
    ],
    'bestebonenmachines.nl' => [
        ['name' => 'Type bonenmachine', 'priority' => 1],
        ['name' => 'Inhoud bonenreservoir (g)', 'priority' => 1],
        ['name' => 'Inhoud waterreservoir (L)', 'priority' => 1],
        ['name' => 'Koffiespecialiteiten (espresso, cappuccino, etc.)', 'priority' => 1],
        ['name' => 'Melksysteem (automatisch/handmatig)', 'priority' => 1],
        ['name' => 'Bedieningsgemak (display/knoppen)', 'priority' => 2],
        ['name' => 'Aantal kopjes tegelijk', 'priority' => 2],
        ['name' => 'Instelbare maalgraad', 'priority' => 2],
        ['name' => 'Instelbare koffiesterkte', 'priority' => 2],
        ['name' => 'Instelbare temperatuur', 'priority' => 3],
        ['name' => 'Automatisch reinigingssysteem', 'priority' => 2],
        ['name' => 'Melkreservoir afneembaar', 'priority' => 3],
        ['name' => 'Afneembaar waterreservoir', 'priority' => 3],
        ['name' => 'Vermogen (Watt)', 'priority' => 2],
        ['name' => 'Snoerlengte', 'priority' => 3],
        ['name' => 'Kopjeswarmer', 'priority' => 3],
        ['name' => 'Geschikt voor gemalen koffie', 'priority' => 2],
        ['name' => 'App-connectie', 'priority' => 3],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Afmetingen', 'priority' => 3],
    ],
    'bestedeurbelmetcamera.nl' => [
        ['name' => 'Beeldresolutie', 'priority' => 1],
        ['name' => 'Live meekijken via app', 'priority' => 1],
        ['name' => 'Tweerichtingsaudio', 'priority' => 1],
        ['name' => 'Bewegingsdetectie', 'priority' => 1],
        ['name' => 'Geluidsdetectie', 'priority' => 2],
        ['name' => 'Nachtzicht (IR)', 'priority' => 1],
        ['name' => 'Opslagmogelijkheden (cloud/SD)', 'priority' => 2],
        ['name' => 'Bedraad of draadloos', 'priority' => 2],
        ['name' => 'Compatibel met Google/Alexa', 'priority' => 2],
        ['name' => 'IP-certificering (waterdicht)', 'priority' => 2],
        ['name' => 'Installatiegemak', 'priority' => 2],
        ['name' => 'Ingebouwde bel', 'priority' => 2],
        ['name' => 'Verbindingsoptie (WiFi/ethernet)', 'priority' => 2],
        ['name' => 'Oplaadtype (USB/net)', 'priority' => 3],
        ['name' => 'Batterijduur (indien draadloos)', 'priority' => 2],
        ['name' => 'App-notificaties', 'priority' => 1],
        ['name' => 'Kijkhoek (graden)', 'priority' => 2],
        ['name' => 'Tijdschema instelbaar', 'priority' => 3],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Garantie', 'priority' => 2],
    ],
    'besteslowcookerkopen.nl' => [
        ['name' => 'Inhoud (liter)', 'priority' => 1],
        ['name' => 'Aantal standen (laag/hoog/warmhouden)', 'priority' => 1],
        ['name' => 'Timerfunctie', 'priority' => 1],
        ['name' => 'Automatische warmhoudfunctie', 'priority' => 2],
        ['name' => 'Vermogen (Watt)', 'priority' => 2],
        ['name' => 'Uitneembare binnenpan', 'priority' => 1],
        ['name' => 'Materiaal binnenpan (keramisch, aluminium)', 'priority' => 2],
        ['name' => 'Transparant deksel', 'priority' => 2],
        ['name' => 'Digitaal display', 'priority' => 2],
        ['name' => 'Geschikt voor oven', 'priority' => 3],
        ['name' => 'Geschikt voor vaatwasser', 'priority' => 2],
        ['name' => 'Antiaanbaklaag', 'priority' => 2],
        ['name' => 'Handgrepen koelblijvend', 'priority' => 3],
        ['name' => 'Snoerlengte', 'priority' => 3],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Warmhoudtijd (maximaal)', 'priority' => 3],
        ['name' => 'Receptenboek inbegrepen', 'priority' => 3],
        ['name' => 'App-functionaliteit', 'priority' => 3],
        ['name' => 'Startuitstel', 'priority' => 3],
        ['name' => 'Vorm (ovaal/ronde pan)', 'priority' => 2],
    ],
    'crosstrainertest.nl' => [
        ['name' => 'Type aandrijving (voor/achter)', 'priority' => 1],
        ['name' => 'Aantal trainingsprogramma’s', 'priority' => 1],
        ['name' => 'Weerstandsniveaus', 'priority' => 1],
        ['name' => 'Vliegwielgewicht', 'priority' => 1],
        ['name' => 'Maximaal belastbaar gewicht', 'priority' => 2],
        ['name' => 'Hartslagmeting', 'priority' => 1],
        ['name' => 'Connectiviteit (Bluetooth/app)', 'priority' => 2],
        ['name' => 'Display met trainingsdata', 'priority' => 2],
        ['name' => 'Verstelbare pedalen', 'priority' => 2],
        ['name' => 'Vliegwielmassa', 'priority' => 2],
        ['name' => 'Afmetingen', 'priority' => 3],
        ['name' => 'Transportwieltjes', 'priority' => 3],
        ['name' => 'Stroomvoorziening (net/batterij)', 'priority' => 3],
        ['name' => 'Opklapbaar', 'priority' => 3],
        ['name' => 'Gebruik (thuis/semi-prof)', 'priority' => 2],
        ['name' => 'Garantie', 'priority' => 2],
        ['name' => 'Geluid tijdens gebruik', 'priority' => 3],
        ['name' => 'Bidonhouder', 'priority' => 3],
        ['name' => 'Max. lengte gebruiker', 'priority' => 3],
        ['name' => 'Verstelbare handgrepen', 'priority' => 2],
    ],
    'kattenvoerautomaat.nl' => [
        ['name' => 'Inhoud voerreservoir (gram)', 'priority' => 1],
        ['name' => 'Aantal maaltijden per dag instelbaar', 'priority' => 1],
        ['name' => 'Portiegrootte instelbaar', 'priority' => 1],
        ['name' => 'Timerfunctie', 'priority' => 1],
        ['name' => 'Geschikt voor nat/droogvoer', 'priority' => 2],
        ['name' => 'Werkt op stroom/batterij', 'priority' => 2],
        ['name' => 'Aantal voerbakken', 'priority' => 2],
        ['name' => 'App-bediening mogelijk', 'priority' => 2],
        ['name' => 'Camera inbegrepen', 'priority' => 3],
        ['name' => 'Stembestand inspreekbaar', 'priority' => 3],
        ['name' => 'Voerfrequentie instelbaar', 'priority' => 2],
        ['name' => 'Vaatwasserbestendige onderdelen', 'priority' => 2],
        ['name' => 'Vergrendelingsmechanisme deksel', 'priority' => 3],
        ['name' => 'Design & kleur', 'priority' => 3],
        ['name' => 'Anti-slip onderkant', 'priority' => 3],
        ['name' => 'Materiaal', 'priority' => 3],
        ['name' => 'LCD-display', 'priority' => 2],
        ['name' => 'Verbinding via WiFi', 'priority' => 3],
        ['name' => 'Geluidsnotificatie dier', 'priority' => 3],
        ['name' => 'Aantal huisdieren geschikt', 'priority' => 2],
    ],
    'loopbandentest.nl' => [
        ['name' => 'Maximale snelheid (km/u)', 'priority' => 1],
        ['name' => 'Motorvermogen (pk)', 'priority' => 1],
        ['name' => 'Hellingshoek instelbaar', 'priority' => 1],
        ['name' => 'Aantal programma’s', 'priority' => 1],
        ['name' => 'Loopoppervlak (cm)', 'priority' => 1],
        ['name' => 'Dempingssysteem', 'priority' => 2],
        ['name' => 'Inklapbaar', 'priority' => 2],
        ['name' => 'Hartslagmeting', 'priority' => 2],
        ['name' => 'Bluetooth & app-connectie', 'priority' => 2],
        ['name' => 'Geschikt voor hardlopen/joggen', 'priority' => 1],
        ['name' => 'Gewicht toestel', 'priority' => 3],
        ['name' => 'Maximaal gebruikersgewicht', 'priority' => 2],
        ['name' => 'Display met afstand/snelheid', 'priority' => 2],
        ['name' => 'Stroomvoorziening', 'priority' => 3],
        ['name' => 'Transportwieltjes', 'priority' => 3],
        ['name' => 'Gebruik (thuis/semi-prof)', 'priority' => 2],
        ['name' => 'Opbergvakjes/tablethouder', 'priority' => 3],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Vouwmechanisme (soft drop)', 'priority' => 2],
        ['name' => 'Garantie', 'priority' => 2],
    ],
    'roeitrainertest.nl' => [
        ['name' => 'Type weerstand (lucht, water, magnetisch)', 'priority' => 1],
        ['name' => 'Weerstandsniveaus', 'priority' => 1],
        ['name' => 'Display met tijd/afstand/calorieën', 'priority' => 1],
        ['name' => 'Opklapbaar design', 'priority' => 2],
        ['name' => 'Maximaal belastbaar gewicht', 'priority' => 2],
        ['name' => 'Lengte rails (geschikt voor lange mensen)', 'priority' => 2],
        ['name' => 'Bluetooth-connectie', 'priority' => 2],
        ['name' => 'Hartslagmeting mogelijk', 'priority' => 2],
        ['name' => 'Gewicht roeitrainer', 'priority' => 3],
        ['name' => 'Afmetingen ingeklapt', 'priority' => 3],
        ['name' => 'Comfort zitvlak', 'priority' => 3],
        ['name' => 'Vliegwielgewicht (kg)', 'priority' => 2],
        ['name' => 'Transportwieltjes', 'priority' => 3],
        ['name' => 'Materiaal frame', 'priority' => 3],
        ['name' => 'Pedalen met straps', 'priority' => 3],
        ['name' => 'Programma’s vooraf ingesteld', 'priority' => 2],
        ['name' => 'Gebruik (thuis/semi-prof)', 'priority' => 2],
        ['name' => 'Kleur', 'priority' => 3],
        ['name' => 'Inclusief trainings-app', 'priority' => 3],
        ['name' => 'Garantie', 'priority' => 2],
    ],
    'beste-elektrischemassagekussen.nl' => [
        ['name' => 'Type massage (shiatsu, vibratie, etc.)', 'priority' => 1],
        ['name' => 'Warmtefunctie', 'priority' => 1],
        ['name' => 'Instelbare intensiteit', 'priority' => 2],
        ['name' => 'Timerfunctie', 'priority' => 2],
        ['name' => 'Aantal massagekoppen', 'priority' => 2],
        ['name' => 'Gebruik op nek/rug/schouders', 'priority' => 1],
        ['name' => 'Auto-stop functie', 'priority' => 2],
        ['name' => 'Gebruik in auto mogelijk', 'priority' => 2],
        ['name' => 'Oplaadtype (USB/adapter)', 'priority' => 2],
        ['name' => 'Draadloos of met snoer', 'priority' => 2],
        ['name' => 'Accuduur', 'priority' => 3],
        ['name' => 'Kleur en design', 'priority' => 3],
        ['name' => 'Materiaal bekleding', 'priority' => 3],
        ['name' => 'Snoerlengte', 'priority' => 3],
        ['name' => 'Bevestigingsbanden aanwezig', 'priority' => 3],
        ['name' => 'Maximale geluidsniveau (dB)', 'priority' => 3],
        ['name' => 'Inclusief opbergtas', 'priority' => 3],
        ['name' => 'CE-keurmerk', 'priority' => 3],
        ['name' => 'Garantie', 'priority' => 2],
        ['name' => 'Bediening via afstandsbediening', 'priority' => 2],
    ],
    'elektrischetandenborsteltest.nl' => [
        ['name' => 'Type technologie (roterend/sonisch)', 'priority' => 1],
        ['name' => 'Poetstijd per acculading', 'priority' => 1],
        ['name' => 'Aantal poetsstanden', 'priority' => 1],
        ['name' => 'Timer (2 minuten)', 'priority' => 1],
        ['name' => 'Druksensor', 'priority' => 2],
        ['name' => 'Bluetooth-app connectie', 'priority' => 2],
        ['name' => 'Aantal opzetborstels meegeleverd', 'priority' => 2],
        ['name' => 'Reisetui inbegrepen', 'priority' => 2],
        ['name' => 'Oplaadstation / USB', 'priority' => 2],
        ['name' => 'Kleur/design', 'priority' => 3],
        ['name' => 'Poetsdruksensor met feedback', 'priority' => 2],
        ['name' => 'Geschikt voor beugels', 'priority' => 2],
        ['name' => 'Waterdicht (IP rating)', 'priority' => 2],
        ['name' => 'Smart functies (AI-coaching)', 'priority' => 3],
        ['name' => 'Trillingsaantal per minuut', 'priority' => 2],
        ['name' => 'Indicatie voor vervanging opzetborstel', 'priority' => 3],
        ['name' => 'Inclusief tongreiniger', 'priority' => 3],
        ['name' => 'Kindvriendelijke functie', 'priority' => 3],
        ['name' => 'Garantie', 'priority' => 2],
        ['name' => 'Laadindicator', 'priority' => 3],
    ],
    'bestebabyfoonmetcamera.nl' => [
        ['name' => 'Beeldkwaliteit (resolutie)', 'priority' => 1],
        ['name' => 'Terugspreekfunctie (2-weg audio)', 'priority' => 1],
        ['name' => 'Bereik binnen/buiten', 'priority' => 1],
        ['name' => 'Slaapliedjes', 'priority' => 2],
        ['name' => 'Nachtzichtfunctie', 'priority' => 1],
        ['name' => 'Temperatuursensor', 'priority' => 2],
        ['name' => 'Bewegingsdetectie', 'priority' => 2],
        ['name' => 'Verbinden via WiFi of DECT', 'priority' => 1],
        ['name' => 'App-ondersteuning', 'priority' => 2],
        ['name' => 'Meerdere camera’s koppelbaar', 'priority' => 2],
        ['name' => 'Opnamefunctie', 'priority' => 3],
        ['name' => 'Kijkhoek camera', 'priority' => 3],
        ['name' => 'Op afstand bestuurbaar', 'priority' => 2],
        ['name' => 'Draadloos bereik', 'priority' => 2],
        ['name' => 'Batterijduur ouderunit', 'priority' => 2],
        ['name' => 'Displaygrootte ouderunit', 'priority' => 3],
        ['name' => 'Montageopties', 'priority' => 3],
        ['name' => 'Kleur/design', 'priority' => 3],
        ['name' => 'Garantie', 'priority' => 2],
        ['name' => 'Beeld en geluid apart instelbaar', 'priority' => 2],
    ],

];
